name: resperia
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0

  flutter_svg: ^2.0.2

  cached_network_image: ^3.0.0
  octo_image: ^1.0.0+1

  flutter_spinkit: ^5.0.0

  get_it: ^7.1.3

  flutter_secure_storage: ^8.0.0

  dartz: ^0.10.0

  google_fonts: ^4.0.3

  dio: ^5.0.1
  pretty_dio_logger: ^1.2.0-beta-1

  flutter_bloc: ^8.0.0
  equatable: ^2.0.3

  flutter_form_bloc: ^0.29.3

  image_picker: ^0.8.4+2

  awesome_dialog: ^3.0.2

  animations: ^2.0.1

  auto_route: ^5.0.4

  jiffy: ^5.0.0

  logger: ^1.1.0

  flutter_easyloading: ^3.0.3

  enum_to_string: ^2.0.1

  json_annotation: ^4.4.0
  flutter_speed_dial: ^6.2.0
  easy_localization: ^3.0.0

  flutter_sound: ^9.2.10

  permission_handler: ^10.2.0

  audio_session: ^0.1.6+1

  just_audio: ^0.9.11

  path_provider: ^2.0.9

  provider: ^6.0.0

  file_picker: ^5.2.5

dev_dependencies:
  auto_route_generator: ^5.0.3
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.0.4
  pedantic: ^1.11.0
  build_runner:
  json_serializable: ^6.1.6
  flutter_launcher_icons: ^0.12.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true
