# Generated by Django 3.2.12 on 2022-07-05 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital_location',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.hospital'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.hospital'),
        ),
        migrations.AddField(
            model_name='patient',
            name='isDeathApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default='NEGATIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HOSPITAL', 'Hospital'), ('DOCTOR', 'Doctor'), ('PATIENT', 'Patient')], default='PATIENT', max_length=10),
        ),
    ]
