# Generated by Django 3.2.12 on 2022-07-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220706_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
    ]
